name: Actions Ping

on:
  workflow_dispatch:
  push:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Actions trigger
        run: echo "GitHub Actions is running for $GITHUB_SHA"
